### ISSUE TITLE
Returns of a metric are same

### ISSUE THREAD

**Issue by godspeed1989** [YimianDai/open-alcnet#4]
https://github.com/YimianDai/open-alcnet/blob/08b165b682c3cbadfee76e88aacf7d09ed9d9131/metric/samplewise.py#L65

Is it the calculated nIoU?

**Comment by YimianDai** [comment]
Thanks for pointing this. The code is ugly. However, it is not wrong. In the script, I only use one return value for nIoU. I didn't mistake nIoU as IoU. 

`_, nIoU = self.nIoU_metric.get()`

Thanks again for pointing this. In the next version, I will re-implement these ugly code to a new and well-structured version.
