### ISSUE TITLE
Why not use threshold to calculate IoU but nIoU?

### ISSUE THREAD

**Issue by godspeed1989** [YimianDai/open-alcnet#5]
When we calculate IoU
https://github.com/YimianDai/open-alcnet/blob/08b165b682c3cbadfee76e88aacf7d09ed9d9131/metric/sigmoid.py#L109
and nIoU
https://github.com/YimianDai/open-alcnet/blob/08b165b682c3cbadfee76e88aacf7d09ed9d9131/metric/samplewise.py#L83

**Comment by YimianDai** [comment]
Sorry for replying late... I didn't notice here are some issues if not someone reminds me.

They are exactly the same. 

The score_thresh is 0.5. 

Sigmoid(0) = 0.5.

The first line code `output.asnumpy()` is a logit, the input of a sigmoid. 

Therefore `output.asnumpy() > 0` is the same as  `nd.sigmoid(output).asnumpy() > 0.5`
