### ISSUE TITLE
论文细节上的几点疑惑

### ISSUE THREAD

**Issue by shonehang** [YimianDai/open-alcnet#6]
首先感谢你这篇论文提供了启发性的思路 但当尝试复现的时候有几点疑惑：

①MPCMResNetFPN中似乎没有用到空洞卷积 而PCMNet、MPCMNet都用到了 
https://github.com/YimianDai/open-alcnet/blob/master/model/contrast.py#L129
并且公式4的操作CalMPCM()也没有出现在MPCMResNetFPN函数
https://github.com/YimianDai/open-alcnet/blob/master/model/contrast.py#L358
也只出现在LayerwiseMPCMNet中

②移位函数circ_shift(cen, shift)中的cen代表的是什么？ 它代表的是卷积网络生成的特征图吗，如果是的话，那么只进行一轮的circ_shift操作生成的不是一个点吗？而不是一个局部对比图（矩阵）。不应该遍历整个特征图吗？
![问题2](https://user-images.githubusercontent.com/11374747/120739720-79ecf900-c524-11eb-8489-1fc650f69db8.JPG)

③BLAM结构中两次PWconv的目的是为了统一通道是吗？ 但是这样操作圈乘的通道统一了，圈加操作的通道还没有统一？
![问题3](https://user-images.githubusercontent.com/11374747/120739740-81ac9d80-c524-11eb-9fc2-9fe66bf75ebf.JPG)

感谢解答~

**Comment by YimianDai** [comment]
您好，我先回答第一点，论文全文都没有 claim 我是用了 空洞卷积，我只是用到了 dilation 这个概念，也就是参与计算 PCM  的特征点之间的距离，这个距离在卷积网络里面被叫作 dilation；只是文章里的局部对比度模块 和 空洞卷积都用到了 dilation 这个概念，文章并没有说用了空洞卷积。

还有对于您提出的 MPCMResNetFPN 函数没有用到计算 MPCM 这个疑惑，我代码里的的确确是有的而且 MPCMResNetFPN 也的的确确用到了。 MPCMResNetFPN 下面定义了 `cal_mpcm` 函数，这个在代码 679 行；`cal_mpcm` 函数也被调用了，在代码 539、558、609 都有体现。

**Comment by YimianDai** [comment]
关于第三个问题，X 和 Y 是大小相同的特征图，都是 CxHxW；在进入这个模块之前就已经将其变换成一样大小的了。关于这点，您可以看我的另一篇论文专门做特征融合的论文，讲述地更为细致 https://arxiv.org/abs/2009.14082

**Comment by YimianDai** [comment]
关于第二个问题，循环移位是对整个特征图移位，cen 表示当前特征点，B1 到 B8 代表周围的特征点（cen 和 B 之间的有 dilation）。

提出循环移位的目的就是 为了将对比度计算由一个个像素点分别计算对比度然后依次遍历整个特征图  转化为对整个特征图的操作，这样会快上很多。这个技巧不仅仅对特征图好用，对于传统的局部对比度度量方法也好用，我们在传统方法上也试过，大概可以加速 15%-20% 以上，但是也是有代价 的，就是内存消耗会多很多。

**Comment by shonehang** [comment]
> 关于第二个问题，循环移位是对整个特征图移位，cen 表示当前特征点，B1 到 B8 代表周围的特征点（cen 和 B 之间的有 dilation）。
> 
> 提出循环移位的目的就是 为了将对比度计算由一个个像素点分别计算对比度然后依次遍历整个特征图 转化为对整个特征图的操作，这样会快上很多。这个技巧不仅仅对特征图好用，对于传统的局部对比度度量方法也好用，我们在传统方法上也试过，大概可以加速 15%-20% 以上，但是也是有代价 的，就是内存消耗会多很多。

感谢你的回复第一点明白了
第三个问题会再阅读你的另一篇论文
第二个问题 cen 表示当前特征点
可是看代码中cen[:, :, shift:, wid-shift:] 的结构 这应该是个特征图呀？
另外看到你在其他issue的回复中说visualize_local_contrast_networks.py就是测试程序
https://github.com/YimianDai/open-alcnet/blob/master/visualize_local_contrast_networks.py#L10  
会报错
Traceback (most recent call last):
  File "visualize_local_contrast_networks.py", line 10, in <module>
    from utils import summary
ModuleNotFoundError: No module named 'utils'

**注释掉这一行后继续运行报错
RuntimeError: Parameter 'mpcmresnetfpn0_batchnorm0_gamma' was not initialized on context cpu(0). It was only initialized on [gpu(0)].**
$ python visualize_local_contrast_networks.py
Number of GPUs: 1
Namespace(base_size=256, batch_size=1, blocks=4, channels=16, colab=False, crop_size=240, ctx=[gpu(0)], cue='lcm', dataset='DENTIST', dtype='float32', epochs=300, eval=False, gamma=2, gpus='0', iou_thresh=0.5, kvstore='device', lambd=1, lr=0.1, lr_decay=0.1, lr_decay_epoch='100,200', metric='mAP', momentum=0.9, net_choice='MPCMResNetFPN', no_cuda=False, no_val=False, no_wd=False, norm_kwargs={}, norm_layer=<class 'mxnet.gluon.nn.basic_layers.BatchNorm'>, pyramid_fuse='bottomuplocal', pyramid_mode='Dec', resume=None, scale_mode='Multiple', score_thresh=0.5, shift=13, sparsity=False, start_epoch=0, syncbn=False, test_batch_size=1, train_split='trainval', val_split='test', wd=0.0001, weight_decay=0.0001, workers=48)
net_choice:  MPCMResNetFPN
net_choice:  MPCMResNetFPN
scale_mode:  Multiple
pyramid_fuse:  bottomuplocal
layers:  [4, 4, 4]
channels:  [8, 16, 32, 64]
shift:  13
Starting Epoch: 0
Total Epochs: 300
Traceback (most recent call last):
  File "visualize_local_contrast_networks.py", line 254, in <module>
    trainer.validation(0)
  File "visualize_local_contrast_networks.py", line 227, in validation
    pred = self.net(exp_img)
  File "/mistgpu/site-packages/mxnet/gluon/block.py", line 682, in __call__
    out = self.forward(*args)
  File "/mistgpu/site-packages/mxnet/gluon/block.py", line 1309, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/home/mist/open-alcnet-master/model/contrast.py", line 518, in hybrid_forward
    x = self.stem(x)      # sub 2
  File "/mistgpu/site-packages/mxnet/gluon/block.py", line 682, in __call__
    out = self.forward(*args)
  File "/mistgpu/site-packages/mxnet/gluon/block.py", line 1309, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/mistgpu/site-packages/mxnet/gluon/nn/basic_layers.py", line 119, in hybrid_forward
    x = block(x)
  File "/mistgpu/site-packages/mxnet/gluon/block.py", line 682, in __call__
    out = self.forward(*args)
  File "/mistgpu/site-packages/mxnet/gluon/block.py", line 1302, in forward
    params = {k: v.data(ctx) for k, v in self._reg_params.items()}
  File "/mistgpu/site-packages/mxnet/gluon/block.py", line 1302, in <dictcomp>
    params = {k: v.data(ctx) for k, v in self._reg_params.items()}
  File "/mistgpu/site-packages/mxnet/gluon/parameter.py", line 574, in data
    return self._check_and_get(self._data, ctx)
  File "/mistgpu/site-packages/mxnet/gluon/parameter.py", line 228, in _check_and_get
    self.name, str(ctx), str(self._ctx_list)))
RuntimeError: Parameter 'mpcmresnetfpn0_batchnorm0_gamma' was not initialized on context cpu(0). It was only initialized on [gpu(0)].


**命令后面加上--no-cuda  报错AttributeError: 'NDArray' object has no attribute 'view'**
$ python visualize_local_contrast_networks.py --no-cuda
Using CPU
Namespace(base_size=256, batch_size=1, blocks=4, channels=16, colab=False, crop_size=240, ctx=[cpu(0)], cue='lcm', dataset='DENTIST', dtype='float32', epochs=300, eval=False, gamma=2, gpus='0', iou_thresh=0.5, kvstore='local', lambd=1, lr=0.1, lr_decay=0.1, lr_decay_epoch='100,200', metric='mAP', momentum=0.9, net_choice='MPCMResNetFPN', no_cuda=True, no_val=False, no_wd=False, norm_kwargs={}, norm_layer=<class 'mxnet.gluon.nn.basic_layers.BatchNorm'>, pyramid_fuse='bottomuplocal', pyramid_mode='Dec', resume=None, scale_mode='Multiple', score_thresh=0.5, shift=13, sparsity=False, start_epoch=0, syncbn=False, test_batch_size=1, train_split='trainval', val_split='test', wd=0.0001, weight_decay=0.0001, workers=48)
net_choice:  MPCMResNetFPN
net_choice:  MPCMResNetFPN
scale_mode:  Multiple
pyramid_fuse:  bottomuplocal
layers:  [4, 4, 4]
channels:  [8, 16, 32, 64]
shift:  13
Starting Epoch: 0
Total Epochs: 300
Traceback (most recent call last):
  File "visualize_local_contrast_networks.py", line 254, in <module>
    trainer.validation(0)
  File "visualize_local_contrast_networks.py", line 228, in validation
    plt.imsave(save_path + img_id + '.png', pred)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py", line 2251, in imsave
    return matplotlib.image.imsave(fname, arr, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/image.py", line 1577, in imsave
    rgba = sm.to_rgba(arr, bytes=True)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/cm.py", line 332, in to_rgba
    x = self.norm(x)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/colors.py", line 1046, in __call__
    self.autoscale_None(result)
  File "/usr/local/lib/python3.6/dist-packages/matplotlib/colors.py", line 1090, in autoscale_None
    self.vmin = A.min()
  File "/usr/local/lib/python3.6/dist-packages/numpy/ma/core.py", line 5673, in min
    axis=axis, out=out, **kwargs).view(type(self))
AttributeError: 'NDArray' object has no attribute 'view'

**另外运行训练代码python train_alcnet.py 
其中--net-choice设置为MPCMResNetFPN
--scale-mode设置为Multiple
报错ValueError: unknow self.scale_mode**
$ python train_alcnet.py
Number of GPUs: 1
Namespace(base_size=512, batch_size=2, blocks=4, channels=16, colab=False, crop_size=480, ctx=[gpu(0)], cue='lcm', dataset='DENTIST', dtype='float32', epochs=300, eval=False, gamma=2, gpus='0', iou_thresh=0.5, kvstore='device', lambd=1, lr=0.1, lr_decay=0.1, lr_decay_epoch='100,200', metric='mAP', momentum=0.9, net_choice='MPCMResNetFPN', no_cuda=False, no_val=False, no_wd=False, norm_kwargs={}, norm_layer=<class 'mxnet.gluon.nn.basic_layers.BatchNorm'>, pyramid_fuse='sk', pyramid_mode='Dec', r=2, resume=None, scale_mode='Multiple', score_thresh=0.5, shift=13, sparsity=False, start_epoch=0, summary=False, syncbn=False, test_batch_size=32, train_split='trainval', val_split='test', wd=0.0001, weight_decay=0.0001, workers=48)
net_choice:  MPCMResNetFPN
net_choice:  MPCMResNetFPN
scale_mode:  Multiple
pyramid_fuse:  sk
r:  2
layers:  [4, 4, 4]
channels:  [8, 16, 32, 64]
shift:  13
Model Initializing
args.ctx:  [gpu(0)]
Starting Epoch: 0
Total Epochs: 300
  0%|                                                                                                                                                                                                 | 0/112 [00:00<?, ?it/s][15:59:05] ../src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
  0%|                                                                                                                                                                                                 | 0/112 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "train_alcnet.py", line 367, in <module>
    trainer.training(epoch)
  File "train_alcnet.py", line 293, in training
    pred = self.net(x)
  File "/mistgpu/site-packages/mxnet/gluon/block.py", line 682, in __call__
    out = self.forward(*args)
  File "/mistgpu/site-packages/mxnet/gluon/block.py", line 1309, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/home/mist/open-alcnet-master/model/contrast.py", line 602, in hybrid_forward
    raise ValueError("unknow self.scale_mode")
ValueError: unknow self.scale_mode



**数据集路径均已修改
我的环境是
cuda                           10.0
mxnet-cu100              1.8.0.post0
autogluon.core           0.2.0
gluoncv                       0.10.1.post0
numpy                        1.19.5**

**Comment by YimianDai** [comment]
在你截取的插图里， Cen 表示当前特征点，B1 一直到 B8 表示跟 Cen 特征点 距离为 d 的特征点。这是基本上所有基于局部对比度的论文都会画的示意图。可以看一下 LCM、MPCM 之类的论文看一下。

然后在程序中，因为对整张图 使用了 循环移位 技巧，所以 cen 就表示当前特征点维持不变的的特征图，B1 一直到 B8 表示的是相应平移了一定位置后的特征图。

没有使用特征图的循环移位技巧，两重 for 循环 逐点计算局部对比度，此时 cen 和 B1 到 B8 如插图所示，都是一张 2D 特征图上的点；
对整张特征图使用循环移位技巧，cen 就变成了 居中的特征图，B1  到 B8 就是平移特定量的特征图，从而只要完成特征图上加减，就可以对所有像素点都完成对比度的计算，就不需要两重 for 循环了。

**Comment by cheeenzq** [comment]
> 首先感谢你这篇论文提供了思想性的思想但当试点复现的时候有宇宙奇迹：
> 
> ①MPCMNetFPN中暗示没有接触空洞牵动PCMNet、MPCMNet都了
> [https://github.comYimianDai/open-alcnet/blob/master/modelcontrast.pyL129](https://github.com/YimianDai/open-alcnet/blob/master/model/contrast.py#L129)
> 并且公式的4CalMPCM()也没有出现在MPCMResNetFPN功能
> https://github.com/YimianDai/open-alcnet/blob/master/model/contrast.py#L358
> 也只出现在LayerwiseMPCMNet中
> 
> ②转移函数circ_shift(cen, shift)中的cen代表的是什么？它代表的是网络生成的特征图吗，如果是的话，那么只进行循环的circ_shift操作生成的不是一个点吗？而不是一个局部对比图（矩阵）。不应该遍历整个特征图吗？
> ![问题2](https://user-images.githubusercontent.com/11374747/120739720-79ecf900-c524-11eb-8489-1fc650f69db8.JPG)
> 
> ③BLAM结构中的强力缠绕PWconv的，这样是不是为了统一绑定是吗？
> ![问题 3](https://user-images.githubusercontent.com/11374747/120739740-81ac9d80-c524-11eb-9fc2-9fe66bf75ebf.JPG)
> 
> 谢谢解答~

您好，我在运行这个网络的时候出现了问题。显示是找不到数据集。请问您可以把你的文件目录给我看一下吗，非常感谢。

**Comment by YimianDai** [comment]
您嘲讽我的 『宇宙奇迹』，我上面不是回答过您么。。。

你说我 MPCMNetFPN 没有用到空洞卷积，可是我上面明明回答过你， MPCMResNetFPN 下面定义了 cal_mpcm 函数，这个在代码 679 行；cal_mpcm 函数还会调用 cal_pcm 计算每一个尺度的 pcm。。。
我上次就回答过您了。。。

总共 HxW 个点，每次计算一个点，则需要遍历特征图（HxW）次。如果对整个特征图操作，则只需要对整个特征图计算一次。这个是 向量化技巧，同时也是很多计算 NLM 时候减少计算量的技巧，通过交换计算顺序来减少冗余计算量。

第三点，论文里说了，X 和 Y 是经过通道变换和上采样之后的特征图，图示的 X 和 Y 是上采样和通道变换之后的特征图，当然不需要表示出来。

最后，您有不明白的，我也很详细的跟你解释了，反倒是您一没有好好看论文，而没有看我上面的回复。何必用这种羞辱人的方式来侮辱我呢？
我既然敢把代码和数据集都放出来，肯定是问心无愧的。

**Comment by YimianDai** [comment]
先说 点 和 特征图，

假设 x, y 是两个点，X，Y 是两个特征图；x - y 表示两个点相间，X -Y 表示 特征图上 对应点相减，是对整个特征图的操作，这叫向量化，是 MATLAB / Numpy 编程加速的一个常见技巧。

画示意图的时候，都是对局部的 patch / 点 画的，所有基于 local contrast 的论文都是如此；但是计算的时候，直接对整个特征图计算，会快上很多。

这篇论文的贡献之一就是 将基于点/patch 的 local contrast 计算，利用循环移位，使得可以直接对 特征图 计算，从而加快计算速度。另外，循环移位这个技巧，在 06 -10 年 非局部均值（non-local means）火的时候非常常见的，真没有那么难理解。不仅可以利用向量化加速计算，还可以减少冗余计算（将 NLM 的计算量从 P^2S^2HW, 降低为 S^2HW）

我文章中有写的不清楚的，你可以好好问，我也会耐心的给你回答，但你没必要来羞辱人。何况，你羞辱我的，我一开始就回答你了，MPCMResNetFPN 调用 cal_mpcm，cal_mpcm 调用 pcm。这个 dilation 是 循环移位的 shift 数值，不是 dilated conv 的那个 dilation。

**Comment by YimianDai** [comment]
你说的最后一个问题，论文里也说得很明白，你要是没看论文，我给你画红圈了

![CleanShot 2021-08-10 at 17 22 01@2x](https://user-images.githubusercontent.com/9448249/128842395-4cc296cd-6d08-4bcc-9635-e77724a291fa.png)

**Comment by cheeenzq** [comment]
非常抱歉，因为我的一时疏忽造成您的不悦了。我并不是上一位问您的人，如果因为我的回复错误造成了您的不悦，我深感抱歉。我是在搜索文章的时候找到了您的文章，想要对文章进行复现。但是在过程中显示“OSError: ~/datasets is not a valid dir. Did you forget to initialize&nbsp;”错误，因为搜索了网站也没有找到相关回答，所以在您的提问区留言。是因为我的回复错误导致了您的不悦，再次诚恳的道歉，请多多包涵。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YimianDai/open-alcnet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月10日(星期二) 下午5:23
***@***.***&gt;;
抄送:&nbsp;"Kuchiki ***@***.******@***.***&gt;;
主题:&nbsp;Re: [YimianDai/open-alcnet] 论文细节上的几点疑惑 (#6)





 
你说的最后一个问题，论文里也说得很明白，你要是没看论文，我给你画红圈了

**Comment by YimianDai** [comment]
数据集要看你自己安放的路径的。在 train_alcnet.py 里面的下面代码， 不同的平台，数据集的路径是不同的。比如如果你用 Linux，把 data_root = os.path.join('~', 'datasets') 替换成 你自己 放数据的地址即可。

```
if platform.system() == "Darwin":
    data_root = os.path.join('~', 'Nutstore Files', 'Dataset')
elif platform.system() == "Linux":
    data_root = os.path.join('~', 'datasets')
    if args.colab:
        # data_root = '/content/gdrive/My Drive/Colab Notebooks/datasets'
        data_root = '/content/datasets'
else:
    raise ValueError('Notice Dataset Path')
```

BTW，过段时间会放出一个 PyTorch 的版本，目前这个 mxnet 版本的代码架构太烂了。

**Comment by cheeenzq** [comment]
好的，感谢您的解答。谢谢。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yimian Dai ***@***.***&gt;
发送时间: 2021年8月12日 12:37
收件人: YimianDai/open-alcnet ***@***.***&gt;
抄送: cheeenzq ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[YimianDai/open-alcnet] 论文细节上的几点疑惑 (#6)





 
数据集要看你自己安放的路径的。在 train_alcnet.py 里面的下面代码， 不同的平台，数据集的路径是不同的。比如如果你用 Linux，把 data_root = os.path.join('~', 'datasets') 替换成 你自己 放数据的地址即可。
 if platform.system() == "Darwin":     data_root = os.path.join('~', 'Nutstore Files', 'Dataset') elif platform.system() == "Linux":     data_root = os.path.join('~', 'datasets')     if args.colab:         # data_root = '/content/gdrive/My Drive/Colab Notebooks/datasets'         data_root = '/content/datasets' else:     raise ValueError('Notice Dataset Path')  
BTW，过段时间会放出一个 PyTorch 的版本，目前这个 mxnet 版本的代码架构太烂了。

**Comment by xiaolong-217** [comment]
请问pytorch版本有了吗

**Comment by haoxinli123** [comment]
> 请问pytorch版本有了吗

请问您有pytorch版本了吗

**Comment by haoxinli123** [comment]
> 数据集要看你自己安放的路径的。在 train_alcnet.py 里面的下面代码， 不同的平台，数据集的路径是不同的。比如如果你用 Linux，把 data_root = os.path.join('~', 'datasets') 替换成 你自己 放数据的地址即可。
> 
> ```
> if platform.system() == "Darwin":
>     data_root = os.path.join('~', 'Nutstore Files', 'Dataset')
> elif platform.system() == "Linux":
>     data_root = os.path.join('~', 'datasets')
>     if args.colab:
>         # data_root = '/content/gdrive/My Drive/Colab Notebooks/datasets'
>         data_root = '/content/datasets'
> else:
>     raise ValueError('Notice Dataset Path')
> ```
> 
> BTW，过段时间会放出一个 PyTorch 的版本，目前这个 mxnet 版本的代码架构太烂了。

请问pytorch版本有了吗
